plugins {
    id 'java'
    id 'org.openjfx.javafxmaven' version '0.1.0'
}

group = 'com.tipcalculator'
version = '1.0-SNAPSHOT'
sourceCompatibility = '17'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.openjfx:javafx-controls:22.0.1'
    implementation 'org.openjfx:javafx-fxml:22.0.1'
}

javafx {
    version = "22.0.1"
    modules = ['javafx.controls', 'javafx.fxml']
}

task runApp(type: JavaExec) {
    mainClass = 'TipCalculator'
    classpath = sourceSets.main.runtimeClasspath
}
